version: '3.7'

services:

  dart-server:
    image: dart-server:1.0.0
    container_name: dart-server
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      # target: development
      # target: production
    # Run a command against the development stage of the image. Comment this if production
    # command: yarn start:dev
    ports:
      - 8080:8080
